### ISSUE TITLE
[Feature Request] Add a flag to handle Unknown licenses

### ISSUE THREAD

**Issue by jcasner** [actions/dependency-review-action#264]
Because it is so difficult to build and maintain a database of all licenses for all packages, it would be great if there were some options for what to do when a package with an unknown license is added.

Option 1: Comment on the PR so someone at least gets a heads up to double check the license manually

Option 2: Allow the option to explicitly deny packages with unknown licenses. 
* Note - we'd probably need to also add a feature to explicitly allow specific packages in this situation...

I'm open to other options, too :) 

Thanks

**Comment by febuiles** [comment]
More details about unknown licenses in https://github.com/actions/dependency-review-action/issues/182#issuecomment-1259983756

**Comment by febuiles** [comment]
@jcasner I'm currently working on improving the license support to get much more complete coverage of projects hosted in GitHub/supported by GitHub's Licenses API. Your second proposal sounds reasonable even with better license coverage, so I think we can do something about this soon. 

The packages allowlist sounds like a "nice to have", but not mandatory in order to block PRs on null licenses. Is this a "someone could want" feature, or would it affect you if we only shipped what's outlined in your "Option 2"?

**Comment by febuiles** [comment]
PR in progress [here](https://github.com/actions/dependency-review-action/pull/284).

**Comment by febuiles** [comment]
@jcasner we've improved license detection following the approach outlined above. We are also reporting unknown licenses in the output, I hope this helps. Closing this issue, please re-open if needed.

**Comment by wmmc88** [comment]
I think a flag to explicitly deny unknown licenses is still warranted.

The following run fails to be able to detect the license of anstyle:
https://github.com/wmmc88/windows-drivers-rs/actions/runs/7632001216/job/20791223328?pr=18

I am unsure why this is the case since the license is available [here](https://github.com/rust-cli/anstyle/tree/main/crates/anstyle). 

In any case, I still think there should be a wail to fail the job if unknown license is encountered. There are situations where you wont catch this in PR comments (ex. if triggered on push, or if triggered on PR from a fork)

**Comment by febuiles** [comment]
@wmmc88 Thanks for your input. Do you mind creating a new issue for your Cargo runs so the problem doesn't get lost in the comments here?

**Comment by wmmc88** [comment]
> @wmmc88 Thanks for your input. Do you mind creating a new issue for your Cargo runs so the problem doesn't get lost in the comments here?

@febuiles created new issue to track: #672
