### ISSUE TITLE
Some Settings In External Configuration Overridden By Inline Defaults

### ISSUE THREAD

**Issue by AlexWilson-GIS** [actions/dependency-review-action#706]
## The Problem

I discovered that the `warn-only` parameter is not settable in an external configuration file by first [seeing it get ignored when set only there](https://github.com/AlexWilson-GIS/test-dependency-review/pull/11), then seeing it honored when [it was set inline](https://github.com/AlexWilson-GIS/test-dependency-review/pull/13). I believe that this is the source of the issue:

The default value for `warn-only` is set here:
https://github.com/actions/dependency-review-action/blob/40eb2b8b00a215a5a327a2de3fdf3d6ab861c1fb/action.yml#L64-L67

This means that this parameter, along with every other parameter that has a default value defined in `action.yml`, will have an inline setting when the code is merging configurations. However, the way that they are merged is problematic:
https://github.com/actions/dependency-review-action/blob/40eb2b8b00a215a5a327a2de3fdf3d6ab861c1fb/src/config.ts#L19-L22

As documented in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_object_literals), whenever two objects are merged using the spread operator, fields in a later object will override fields from an earlier object with the same key. This makes `warn-only` and other settings with default values un-configurable from an external file. This is a problem if you want to distribute one configuration file across PR checks in many repositories, including some owned by others that are subscribing to your settings.

## Suggested Fixes

1. Flip the order in which the settings are merged with the spread operator so that parameters set in the external configuration file override inline settings.
2. Add another boolean parameter that dictates if the inline settings override the external settings, with a default value of `false` in order to fix the bug.
3. Simply remove the default values from all of the parameters except one. They are all denoted as not required in `action.yml`:
https://github.com/actions/dependency-review-action/blob/40eb2b8b00a215a5a327a2de3fdf3d6ab861c1fb/action.yml#L7-L10
https://github.com/actions/dependency-review-action/blob/40eb2b8b00a215a5a327a2de3fdf3d6ab861c1fb/action.yml#L56-L67
...and they are all pulled into the action using functions that denote they are optional:
https://github.com/actions/dependency-review-action/blob/40eb2b8b00a215a5a327a2de3fdf3d6ab861c1fb/src/config.ts#L44-L50
The one exception to this is `repo-token`:
https://github.com/actions/dependency-review-action/blob/40eb2b8b00a215a5a327a2de3fdf3d6ab861c1fb/src/dependency-graph.ts#L13
...however, tokens shouldn't be hardcoded into config files anyway, so that's not an issue like the others.
4. Move the setting of each default value into the underlying code after checking to see if the parameter in question is not set in the inline configuration or an external settings file. This is the only suggested solution that isn't a breaking change, but it also makes the code more messy, since there are now three places that parameters could be set.

**Comment by febuiles** [comment]
@AlexWilson-GIS thank you for the very detailed report. Can you test the Action with the branch `remove-warn-default` and see if it fixes the issue?

>         uses: actions/dependency-review-action@remove-warn-default

Pull request up here: https://github.com/actions/dependency-review-action/pull/722

**Comment by AlexWilson-GIS** [comment]
Unfortunately, it appears to still be failing.

**Comment by febuiles** [comment]
@AlexWilson-GIS thanks for the update, we'll try to go through it this week and see what's up. If possible, please leave the reproduction repo up!

**Comment by febuiles** [comment]
@AlexWilson-GIS I think I understand what the problem is now: If you take a look at [the raw log for your PR](https://github.com/AlexWilson-GIS/test-dependency-review/actions/runs/8424102061/job/23067267263?pr=16), the error you are running into is `Error: Dependency review detected denied packages.`. The denylist contains the faulty `log4j` package, so it'll fail regardless of `warn_only` or `fail_on_severity`.

I [created this PR](https://github.com/future-funk/didactic-octo-happiness/pull/4) with the same `pom.xml` you are using, but without providing a denylist for `log4j`. You can see it has been marked as a successful run. If you [dig into the logs](https://github.com/future-funk/didactic-octo-happiness/actions/runs/8428540123/job/23081219547?pr=4) however, you can see the vulnerable package:

```
Vulnerabilities
  pom.xml » org.apache.logging.log4j:log4j-core@2.17.0 – Improper Input Validation and Injection in Apache Log4j2 (moderate severity)
    ↪ https://github.com/advisories/GHSA-8489-44mv-ggj8
  Warning: Dependency review detected vulnerable packages.
```

These are two different issues:

1. There is a problem in the latest release and in `main` with the handling of external config files (and other options). [This PR](https://github.com/actions/dependency-review-action/pull/722) provides a fix for that.
2. `warn_only` does not work in conjunction with `deny_list`. This is not a bug, but we might want to reconsider this interaction. The reasons for this behavior are historical, not technical.

I'm marking this as closed and will be merging the PR/doing a new release in the morning. If you feel we should change the behavior of `warn_only` to take `deny_list` into account (understandable!) please open a new issue (cc @jonjanego).

**Comment by AlexWilson-GIS** [comment]
Sounds good, thanks. I will open a new issue to request that.
