### ISSUE TITLE
[BUG] Action Is Now Unable To Parse NPM pURL Without a Namespace

### ISSUE THREAD

**Issue by AlexWilson-GIS** [actions/dependency-review-action#799]
**Describe the bug**
After updating this action, I cannot use it with my existing configuration file because the package deny list contains the pURL `pkg:npm/crypto-js/` or `pkg:npm/crypto-js`. Neither one is parsable by the action. This has made the action unusable for our PR checks if I want to use a deny list.

**To Reproduce**
See my example below:

* When the pURL is set like [this](https://github.com/AlexWilson-GIS/test-dependency-review/blob/2448d8eb5d924ecb20abe59bc469fbed759ab3d7/.github/dependency-review-config.yml#L16), the job output looks like [this](https://github.com/AlexWilson-GIS/test-dependency-review/actions/runs/9963607515).
* When the pURL is set like [this](https://github.com/AlexWilson-GIS/test-dependency-review/blob/a3d3ef34520eabad5ed200cfc33b1fe0fa0acfd4/.github/dependency-review-config.yml#L16), the job output looks like [this](https://github.com/AlexWilson-GIS/test-dependency-review/actions/runs/9963628171).

**Expected behavior**
I would expect whichever of these notations align with the pURL spec to be parsable and usable by the action.

**Action version**
`@v4`

**Examples**
See above.

**Additional context**
This was not always an issue. I was previously using the `@v3` tag on this action, and the pURL `pkg:npm/crypto-js/` worked.

**Comment by juxtin** [comment]
Hi @AlexWilson-GIS, thanks for the report. I noticed in your [config](https://github.com/AlexWilson-GIS/test-dependency-review/blob/main/.github/dependency-review-config.yml#L14-L68) that you're using arrays for the values of `deny_groups` and `deny_packages`. I believe that's the problem, since we actually expect those to be comma-separated strings (see [example](https://github.com/actions/dependency-review-action/blob/main/docs/examples.md#exclude-dependencies-from-their-name-or-groups))

Would you mind trying again with the comma-separated list form?

**Comment by AlexWilson-GIS** [comment]
Thanks for the quick response. Unfortunately, it doesn't appear to have made a difference:
[Attempt 1](https://github.com/AlexWilson-GIS/test-dependency-review/actions/runs/9981115543)
[Attempt 2](https://github.com/AlexWilson-GIS/test-dependency-review/actions/runs/9981135555)

**Comment by AlexWilson-GIS** [comment]
Oh wait, that's 1 string with all of them inside it 😅

**Comment by AlexWilson-GIS** [comment]
Unfortunately, putting all of them in a string and delimiting them with commas as the example shows [doesn't work either](https://github.com/AlexWilson-GIS/test-dependency-review/actions/runs/9981396989/job/27584942985?pr=17). It appears to expect an array of strings, like what I did in my previous attempt.

**Comment by jtomkiew-mng** [comment]
@AlexWilson-GIS
Have you tried [this config](https://github.com/AlexWilson-GIS/test-dependency-review/blob/a3d3ef34520eabad5ed200cfc33b1fe0fa0acfd4/.github/dependency-review-config.yml#L16) (second from yout OG post) but change first value of `deny_packages` from `pkg:npm/crypto-js/` to `pkg:npm/crypto-js`?

The first error you got ([here](https://github.com/AlexWilson-GIS/test-dependency-review/actions/runs/9963607515)) complained about `deny_groups` values **not ending** with `/`, while the second error ([here](https://github.com/AlexWilson-GIS/test-dependency-review/actions/runs/9963628171)) complained that you have `deny_packages` values **ending** with `/`.

**Comment by bteng22** [comment]
Hey @AlexWilson-GIS 
looks like your [first config](https://github.com/AlexWilson-GIS/test-dependency-review/blob/2448d8eb5d924ecb20abe59bc469fbed759ab3d7/.github/dependency-review-config.yml#L16) is missing a `/` for your groups `- 'pkg:maven/log4j/'` and not for the packages

and for your [second config](https://github.com/AlexWilson-GIS/test-dependency-review/blob/a3d3ef34520eabad5ed200cfc33b1fe0fa0acfd4/.github/dependency-review-config.yml#L16) the leading `/` for packages is not needed since it would consider it a namespace

**Comment by bteng22** [comment]
@jtomkiew-mng haha nice catch! Looks like we both were looking at this at the same time 👍

**Comment by AlexWilson-GIS** [comment]
Thanks for your help everyone! The problem was the slashes - the `deny_packages` list doesn't want a slash, and the `deny_groups` one does.
